# Generated by Django 4.0.4 on 2022-06-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookticket',
            name='bus',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bookticket',
            name='fare',
            field=models.FloatField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='bookticket',
            name='route',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bookticket',
            name='seat_num',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
